### ISSUE TITLE
provide an example of r2dbc URL for H2

### ISSUE THREAD

**Issue by 62mkv** [spring-projects-experimental/spring-boot-r2dbc#79]
It seems that, as of version 0.8.0, r2dbc-spi does not accept a validish URL like `r2dbc:h2://file:./build/h2db/db/dbname;DB_CLOSE_DELAY=-1`. 

And the `README` in current repository (corresponding example folder, I mean) does not give any hints as to what might valid URLs look like. So I thought, maybe it's worth adding?

I still can't figure out what the proper URL for "file" H2 protocol should look like

**Comment by snicoll** [comment]
> I still can't figure out what the proper URL for "file" H2 protocol should look like

@62mkv that's more a R2DBC matter, in particular a `r2dbc-h2` matter. If you can't figure it out there, I'd suggest creating an issue that project https://github.com/r2dbc/r2dbc-h2

**Comment by 62mkv** [comment]
just for the sake of history: this seems to be working: 
```
spring:
  r2dbc:
    url: r2dbc:h2:file://././build/h2db/db/dbname;DB_CLOSE_DELAY=-1
    username: dbname
    password:
```
